### ISSUE TITLE
Odd feature in data cube

### ISSUE THREAD

**Issue by lucarizzi** [kcwidev/kderp#7]
We took some data on 17-8-5 and at least one of the data cube show an odd feature.
On the spectrum, it appears as an emission line, centered at 4881.
On the 2d image centered at that lambda, it appears as a bright spaxel, centered around pixel (20,43)

See attached image:

![image](https://user-images.githubusercontent.com/524957/29050327-eef0dde4-7b76-11e7-9a0c-d83a422c69c6.png)

**Comment by kcwidev** [comment]
This is due to a real feature in the flat field images (all three).  It appears to be more than just a dust spec.  It seems to be a genuine dead pixel with values much lower than other low values in the continuum flat images.  This results in a large multiplicative value (~700) in the master flat, while nearly all other values are around 1.0 as expected.  This might have to be fixed during the stage 1 bad pixel fixing step.  Up to now, we've only seen one bad column.  This is the first bad pixel!  I'll look into this and update as soon as I know what the solution will be.

**Comment by kcwidev** [comment]
OK, I have determined that this region of extremely low sensitivity is present even in object images and so it is a genuine CCD bad region.  I have added this small region to the bad pixel maps for the TBO configuration.  I'll have to keep an eye out for the ALL mode data, but so far all we have are bars and arcs in that mode and it's harder to isolate the bad region or even see if it is there.  I have pushed the changes to the repo, pulled them onto the dr machine and reprocessed the 170805 night's data.  That odd feature is no longer present in the data cube from image 54.  Please let me know if you find other bad regions.  None were obvious to me, but it helps to have fresh eyes look things over.  I'm closing this issue, since future bad regions can be easily accommodated by adding them to the bad pixel files.
